window.TOOTOO_CONFIG = {
  owner: 'pushme-pullyou',
  repo: 'pushme-pullyou.github.io',
  appName: 'Pushme-Pullyou',
  storagePrefix: 'pushme-pullyou',
  sourceRepoUrl: 'https://github.com/pushme-pullyou/pushme-pullyou.github.io',
  themeColor: '#6a5acd',
  subtitle: '',
  faviconLetters: 'PP',
  faviconColor: '#6a5acd',
  subtitle: 'a GitHub repository browser',
  headingFontUrl: 'https://fonts.googleapis.com/css2?family=Patua+One&display=swap',
  headingFont: '"Patua One", serif',
  hiddenFiles: [ 'tootoo.config.js' ],
  hiddenFolders: [ 'Images' ],
};
